# Generated by Django 2.2.16 on 2022-02-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Аутентифицированный пользователь'), ('moder', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=5),
        ),
    ]
