# Generated by Django 2.2.16 on 2022-02-21 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220221_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка произведения'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='reviews_cat_name_84397e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['text'], name='reviews_com_text_2c573d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='reviews_com_author__b2bfe4_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='reviews_gen_name_0e1109_idx'),
        ),
    ]
